version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: ["npm", "run", "start:prod"]
