version: '3.8'

services:
  app:
    build: .
    network_mode: "host"
    ports:
      - "80:3000"
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: ["npm", "run", "start:prod"]

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
