version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    # Removido o volume para evitar sobrescrever arquivos essenciais da imagem
    # volumes:
    #   - .:/app
    command: ["npm", "run", "start:prod"]
